### ISSUE TITLE
Link to uploader in mix page doesn't work

### ISSUE THREAD

**Issue by exjam** [rapka/grimearchive#2]
The "Uploaded 29/3/2016 by **ESAD**." link is wrong.
http://grimearchive.org/mix/1083677

Links to:
http://grimearchive.org/uploader/ESAD-undefined

However going to this page manually works and shows a list of mixes uploaded:
http://grimearchive.org/uploader/ESAD

I guess tripcode is undefined:
https://github.com/richardadjogah/grimelist/blob/master/views/mix.jade#L85

**Comment by rapka** [comment]
I somehow totally missed this report back in the day! I believe the issue has been fixed for a while now.
